export const SMS_QUEUE = 'STRATEGIS_SMS_QUEUE';
export const SMS_JOB = 'STRATEGIS_SMS_JOB';
export const SMS_DRIVER = 'STRATEGIS_SMS_DRIVER';

export const TRANSACTION_CALLBACK_QUEUE = 'TRANSACTION_CALLBACK_QUEUE';
export const TRANSACTION_CALLBACK_JOB = 'TRANSACTION_CALLBACK_JOB';
export const TRANSACTION_CALLBACK_DRIVER = 'TRANSACTION_CALLBACK_DRIVER';

export const MOTOR_COVER_QUEUE = 'MOTOR_COVER_QUEUE';
export const MOTOR_COVER_JOB = 'MOTOR_COVER_JOB';
export const MOTOR_COVER_DRIVER = 'MOTOR_COVER_DRIVER';
