export const SMS_QUEUE = 'STRATEGIS_SMS_QUEUE';
export const SMS_JOB = 'STRATEGIS_SMS_JOB';
export const SMS_DRIVER = 'STRATEGIS_SMS_DRIVER';

export const TRANSACTION_CALLBACK_QUEUE = 'TRANSACTION_CALLBACK_QUEUE';
export const MOTOR_TRANSACTION_CALLBACK_JOB = 'MOTOR_TRANSACTION_CALLBACK_JOB';

export const TRAVEL_TRANSACTION_CALLBACK_JOB =
    'TRAVEL_TRANSACTION_CALLBACK_JOB';
export const TRANSACTION_CALLBACK_DRIVER = 'TRANSACTION_CALLBACK_DRIVER';

export const MOTOR_COVER_QUEUE = 'MOTOR_COVER_QUEUE';
export const MOTOR_COVER_JOB = 'MOTOR_COVER_JOB';
export const MOTOR_COVER_DRIVER = 'MOTOR_COVER_DRIVER';

export const PREMIA_CALLBACK_JOB = 'PREMIA_CALLBACK_JOB';

export const TRAVEL_COVER_QUEUE = 'TRAVEL_COVER_QUEUE';
