export enum MotorCoverRequestStatus {
  PENDING = 'PENDING',
  NEEDS_VEHICLE_INFO = 'NEEDS VEHICLE INFO',
  PAID = 'PAID',
  PAYMENT_FAILED = 'PAYMENT FAILED',
  WAIT_FOR_STICKER = 'WAIT FOR STICKER',
  SUCCESS = 'SUCCESS',
  WAITING_FOR_PAYMENT = 'WAIT FOR PAYMENT',
}
