export enum MotorCoverRequestStatus {
    PENDING = 'PENDING',
    NEEDS_VEHICLE_INFO = 'NEEDS VEHICLE INFO',
    PAID = 'PAID',
    PAYMENT_FAILED = 'PAYMENT FAILED',
    WAITING_FOR_PAYMENT = 'WAIT FOR PAYMENT',
    WAIT_FOR_STICKER = 'WAIT FOR STICKER',
    STICKER_PROCESS_FAILED = 'STICKER_PROCESS_FAILED',
    SUCCESS = 'SUCCESS',
}
