export enum MotorUsage {
    PRIVATE = 1,
    COMMERCIAL = 2,
}

export enum MotorUsageType {
    PRIVATE_VEHICLE = 'PRIVATE_VEHICLE',
    MOTOR_CYCLE = 'MOTOR_CYCLE',
    PASSENGER_CARRYING = 'PASSENGER_CARRYING',
    GENERAL_GOODS = 'GENERAL_GOODS',
    TANKERS = 'TANKERS',
    TRAILERS = 'TRAILERS',
    SPECIAL_TYPE = 'SPECIAL_TYPE',
}