export enum MotorUsage {
  PRIVATE = 1,
  COMMERCIAL = 2,
}

export enum MotorUsageType {
  PRIVATE = 'PRIVATE',
  COMMERCIAL_LOGISTICS = 'COMMERCIAL_LOGISTICS',
  COMMERCIAL_PASSENGER = 'COMMERCIAL_PASSENGER',
  SPECIAL_TYPE = 'SPECIAL_TYPE',
}
