export const PUSH_NOTIFICATION_JOB = 'PUSH_NOTIFICATION_JOB';
export const PUSH_NOTIFICATION_QUEUE = 'PUSH_NOTIFICATION_QUEUE';
export const PUSH_NOTIFICATION_DRIVER = 'PUSH_NOTIFICATION_DRIVER';

export const PUSH_NOTIFICATION_TOPIC_JOB = 'PUSH_NOTIFICATION_TOPIC_JOB';
export const PUSH_NOTIFICATION_TOPIC_QUEUE = 'PUSH_NOTIFICATION_TOPIC_QUEUE';
